# A generic, single database configuration.

[alembic]
# path to migration scripts
script_location = alembic

# template used to generate migration file names; during revision
# generation, the alc_version_id, slug, and rev_id variables are available
# file_template = %%(rev)s_%%(slug)s

# timezone to use when rendering the date within the migration file
# leave blank for local time
# timezone =

# max length of characters to prepend to revision file names.
# truncate_slug_length = 40

# set to 'true' to run the environment during
# the 'revision' command, regardless of autogenerate
# revision_environment = false

# set to 'true' to allow .pyc files to be created
# sourceless = false

# version location specification; This defaults
# to alembic/versions.  When using multiple version
# directories, initial revs will be in the first directory,
# and subsequent revs will be in the respective directory
# version_locations = %(here)s/alembic/versions

# version_path_separator = :

# set to 'true' to search for scripts recursively
# recursive_version_locations = false

# the output encoding used when revision files
# are written from script.py.mako
# output_encoding = utf-8

sqlalchemy.url = postgresql://user:pass@localhost/dbname


[post_write_hooks]
# post_write_hooks allows us to define scripts that are run after
# a revision file is generated.

# format using "black" - provide the path to "black" and parameters
# hooks = black
# black.type = console_scripts
# black.entrypoint = black
# black.options = -l 79 REVISION_SCRIPT_FILENAME

# Logging configuration
[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stdout,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
