"""initial_schema

Revision ID: 7ab3605623fc
Revises: 
Create Date: 2026-03-21 11:03:25.882905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ab3605623fc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dining_etiquette',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dining_etiquette_city'), 'dining_etiquette', ['city'], unique=False)
    op.create_index(op.f('ix_dining_etiquette_id'), 'dining_etiquette', ['id'], unique=False)
    op.create_table('planning_states',
    sa.Column('session_id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('state_json', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_index(op.f('ix_planning_states_session_id'), 'planning_states', ['session_id'], unique=False)
    op.create_index(op.f('ix_planning_states_user_id'), 'planning_states', ['user_id'], unique=False)
    op.create_table('restaurants',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.JSON(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('cuisine_type', sa.JSON(), nullable=False),
    sa.Column('avg_price_min', sa.Float(), nullable=False),
    sa.Column('avg_price_max', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('established_year', sa.Integer(), nullable=True),
    sa.Column('stability_rating', sa.Float(), nullable=True),
    sa.Column('meal_periods', sa.JSON(), nullable=True),
    sa.Column('last_updated', sa.String(), nullable=True),
    sa.Column('data_source', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_restaurants_city'), 'restaurants', ['city'], unique=False)
    op.create_index(op.f('ix_restaurants_id'), 'restaurants', ['id'], unique=False)
    op.create_table('share_links',
    sa.Column('token', sa.String(length=32), nullable=False),
    sa.Column('plan_id', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('token')
    )
    op.create_index(op.f('ix_share_links_plan_id'), 'share_links', ['plan_id'], unique=False)
    op.create_index(op.f('ix_share_links_token'), 'share_links', ['token'], unique=False)
    op.create_table('specialty_dishes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('name', sa.JSON(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('price_min', sa.Float(), nullable=True),
    sa.Column('price_max', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_specialty_dishes_city'), 'specialty_dishes', ['city'], unique=False)
    op.create_index(op.f('ix_specialty_dishes_id'), 'specialty_dishes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_specialty_dishes_id'), table_name='specialty_dishes')
    op.drop_index(op.f('ix_specialty_dishes_city'), table_name='specialty_dishes')
    op.drop_table('specialty_dishes')
    op.drop_index(op.f('ix_share_links_token'), table_name='share_links')
    op.drop_index(op.f('ix_share_links_plan_id'), table_name='share_links')
    op.drop_table('share_links')
    op.drop_index(op.f('ix_restaurants_id'), table_name='restaurants')
    op.drop_index(op.f('ix_restaurants_city'), table_name='restaurants')
    op.drop_table('restaurants')
    op.drop_index(op.f('ix_planning_states_user_id'), table_name='planning_states')
    op.drop_index(op.f('ix_planning_states_session_id'), table_name='planning_states')
    op.drop_table('planning_states')
    op.drop_index(op.f('ix_dining_etiquette_id'), table_name='dining_etiquette')
    op.drop_index(op.f('ix_dining_etiquette_city'), table_name='dining_etiquette')
    op.drop_table('dining_etiquette')
    # ### end Alembic commands ###
